server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
              - Path=/userservice/api/v1/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/vehicleservice/api/v1/**
        - id: travel-service
          uri: lb://travel-service
          predicates:
            - Path=/travelservice/api/v1/**
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/hotelservice/api/v1/**
        - id: guide-service
          uri: lb://guide-service
          predicates:
            - Path=/guideservice/api/v1/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
