spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/userservice
      auto-index-creation: true
  application:
    name: user-service

server:
  servlet:
    context-path: /userservice
  port: 8090

security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
    refresh-token:
      expiration: 604800000
